ccoa/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
from django.contrib.auth.views import LoginView as AuthLogin, LogoutView as AuthLogoff

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', include('sendemail.urls', namespace='send_to')),
    path('', include('posts.urls')),
    # path('login', AuthLogin.as_view(), name='login'),
    # path('logout/', AuthLogoff.as_view(), name='logout'),
    path('tinymce/', include('tinymce.urls')),
    path('api/ccoa/v1/gatiri/', include('posts.apiurls')),
    path('api/ccoa/v1/gatiri/', include('rest_framework.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
#     urlpatterns += [
#         re_path(r'^media/(?P<path>.*)$', serve, {
#             'document_root': settings.MEDIA_ROOT,
#         }),
#     ]

sendemail/urls.py
from django.urls import path
from .views import contact_view


app_name = 'send_to'
urlpatterns = [
    path('contact/', contact_view, name='contact'),
]

templates/_footer.html
<footer class="site-footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="widget">
          <h3 class="widget-title">Our address</h3>
          <p>We are located at Banana behind Banana matatu stage</p>
          <br>
          <ul class="address">
            <li><i class="fa fa-map-marker"></i>  Karuri, Kiambu</li>
            <br>
             <li><i class="fa fa-phone"></i> +254727257053</li>
            <br>
            <li><i class="fa fa-envelope"></i> christcovenant2010@gmail.com</li>
            <br>
            <li>
              <i>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class=" fa bi bi-envelope-paper" viewBox="0 0 16 16">
                  <path d="M4 0a2 2 0 0 0-2 2v1.133l-.941.502A2 2 0 0 0 0 5.4V14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V5.4a2 2 0 0 0-1.059-1.765L14 3.133V2a2 2 0 0 0-2-2H4Zm10 4.267.47.25A1 1 0 0 1 15 5.4v.817l-1 .6v-2.55Zm-1 3.15-3.75 2.25L8 8.917l-1.25.75L3 7.417V2a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v5.417Zm-11-.6-1-.6V5.4a1 1 0 0 1 .53-.882L2 4.267v2.55Zm13 .566v5.734l-4.778-2.867L15 7.383Zm-.035 6.88A1 1 0 0 1 14 15H2a1 1 0 0 1-.965-.738L8 10.083l6.965 4.18ZM1 13.116V7.383l4.778 2.867L1 13.117Z"/>
                </svg>
              </i> P.O BOX  1047-00219 Karuri, Kiambu
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="widget">
          <h3 class="widget-title">Quick links</h3>
          <ul class="bullet">
            <li><a href="{% url 'send_to:contact' %}">Contact Us</a></li>
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'photo_gallery_list' %}">Gallery</a></li>
            <li><a href="#">Donations</a></li>
            <li><a href="{% url 'events_list' %}">Events</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-4">
        <div class="widget">
          <h3 class="widget-title">Contact form</h3>
          <form data-email="christcovenant2010@gmail.com" class="contact-form" >
            <div class="row">
              <div class="col-md-6"><input type="text" placeholder="Your name..." required></div>
              <div class="col-md-6"><input type="email" placeholder="Email..." required></div>
            </div>

            <textarea name="" placeholder="Your message..." required></textarea>
            <div class="text-right"><input type="submit" value="Send message"></div>

          </form>
        </div>
      </div>
    </div>
    <p class="colophon text-center">Copyright <i class="fa fa-copyright"></i> 2023  Christ covenant Outreach Assembly Church. All right reserved.</p>
  </div>
</footer> <!-- .site-footer -->
</div>

templates/_navbar.html
{% load static bootstrap5 %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'sass/style.scss' %}">
    <!-- Loading third party fonts -->
    <link href="{% static 'fonts/novecento-font/novecento-font.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fonts/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
{% endblock %}
{% load static bootstrap5 %}
<div class="site-content">
    <header class="site-header">
        <div class="container">
            <a href="{% url 'home' %}" class="branding">
                <img src="{% static 'favicon/church_logo.png' %}" alt="logo" width="75" height="73" class="logo">
                <h1 class="site-title">Christ covenant Outreach Assembly Church</h1>
            </a>

            <div class="main-navigation">
                <button class="menu-toggle"><i class="fa fa-bars"></i> Menu</button>
                <ul class="menu current-menu-item">
                    <li class="menu-item"><a href="{% url 'home' %}">Homepage </a></li>
                    <li class="menu-item"><a href="{% url 'minister_list' %}">Ministers </a></li>
                    <li class="menu-item"><a href="{% url 'sermon_list' %}">Sermons</a></li>
                    <li class="menu-item"><a href="{% url 'events_list' %}">Events</a></li>
                    <li class="menu-item"><a href="{% url 'photo_gallery_list' %}">Gallery</a></li>
<!--							<li class="menu-item"><a href="#">Families</a></li>-->
                    <li class="menu-item"><a href="{% url 'send_to:contact' %}">Contact</a></li>
                </ul>
            </div>
            <div class="mobile-navigation"></div>
        </div>
    </header>
</div>



{% block bootstrap5_extra_script %}
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/min/plugins-min.js' %}"></script>
    <script src="{% static 'js/min/app-min.js' %}"></script>
{% endblock %}
    

templates/admin_navbar.html
{% load static bootstrap5 %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'css/typicons.font/font/typicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/css/vendor.bundle.base.css' %}">    
    <link rel="stylesheet" href="{% static 'css/vertical-layout-light/style.css' %}">
{% endblock %}
<div class="container-scroller">
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
    <a class="navbar-brand" href="{% url 'home' %}">
        <img  src="{% static 'favicon/church_logo.png' %}" alt="logo" width="10px" height="40">
    </a>
    <a class="navbar-brand brand-logo-mini" href="{% url 'home' %}"><img  src="{% static 'favicon/church_logo.png' %}" alt="logo"></a>
    <button class="navbar-toggler navbar-toggler align-self-center d-none d-lg-flex" type="button" data-toggle="minimize">
        <span class="typcn typcn-th-menu"></span>
    </button>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
    <ul class="navbar-nav mr-lg-2">
        <li class="nav-item  d-none d-lg-flex">
        <a class="nav-link" href="#">
            Calendar
        </a>
        </li>
        <li class="nav-item  d-none d-lg-flex">
        <a class="nav-link active" href="#">
            Statistic
        </a>
        </li>
        <li class="nav-item  d-none d-lg-flex">
        <a class="nav-link" href="#">
            Employee
        </a>
        </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
        <li class="nav-item d-none d-lg-flex  mr-2">
        <a class="nav-link" href="#">
            Help
        </a>
        </li>

        <li class="nav-item nav-profile dropdown">
        <a class="nav-link dropdown-toggle  pl-0 pr-0" href="#" data-toggle="dropdown" id="profileDropdown">
            <i class="typcn typcn-user-outline mr-0"></i>
            <span class="nav-profile-name"><strong>{{user.username}}</strong></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
            <a class="dropdown-item">
            <i class="typcn typcn-cog text-primary"></i>
            Settings
            </a>
            <a class="dropdown-item" href="{% url 'logout' %}">
            <i class="typcn typcn-power text-primary"></i>
            Logout
            </a>
        </div>
        </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <span class="typcn typcn-th-menu"></span>
    </button>
    </div>
</nav>
<div class="container-fluid page-body-wrapper">
    <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
            <li class="nav-item">
                <div class="d-flex sidebar-profile">
                <div class="sidebar-profile-image">
                    <img src="{{user.photo.url}}" alt="image">
                    <span class="sidebar-status-indicator"></span>
                </div>
                <div class="sidebar-profile-name">
                    <p class="sidebar-name">
                    {{user.username}}
                    </p>
                    <p class="sidebar-designation">
                    Welcome
                    </p>
                </div>
                </div>
                <div class="nav-search">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Type to search..." aria-label="search" aria-describedby="search">
                    <div class="input-group-append">
                    <span class="input-group-text" id="search">
                        <i class="typcn typcn-zoom"></i>
                    </span>
                    </div>
                </div>
                </div>
                <p class="sidebar-menu-title">Dash menu</p>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">
                <i class="typcn typcn-home menu-icon"></i>
                <span class="menu-title">Home <span class="badge badge-primary ml-3">New</span></span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'minister_list' %}">
                <i class="typcn typcn-film menu-icon"></i>
                <span class="menu-title">Ministers</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'sermon_list' %}"">
                <!-- <i class="typcn typcn-user menu-icon"></i> -->
                <i class="typcn typcn-book menu-icon"></i>
                <span class="menu-title">Sermons</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'events_list' %}">
                <i class="typcn typcn-calendar menu-icon"></i>
                <span class="menu-title">Events</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'photo_gallery_list' %}">
                <i class="typcn typcn-image menu-icon"></i>
                <span class="menu-title">Gallery</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'send_to:contact' %}">
                <i class="typcn typcn-device-phone  menu-icon"></i>
                <span class="menu-title">Contact Us</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#auth" aria-expanded="false" aria-controls="auth">
                <i class="typcn typcn-user-add-outline menu-icon"></i>
                <span class="menu-title">User Pages</span>
                <i class="menu-arrow"></i>
                </a>
                <div class="collapse" id="auth">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"> <a class="nav-link" href="{% url 'login' %}"> Login </a></li>
                    <li class="nav-item"> <a class="nav-link" href="pages/samples/register.html"> Register </a></li>
                </ul>
                </div>
            </li>
        </ul>
    </nav>
    
    <div class="main-panel">
        <div class="content-wrapper">
            <div id="settings-trigger"><i class="typcn typcn-cog-outline"></i></div>
            <div id="theme-settings" class="settings-panel">
                <i class="settings-close typcn typcn-delete-outline"></i>
                <p class="settings-heading">SIDEBAR SKINS</p>
                <div class="sidebar-bg-options" id="sidebar-light-theme">
                    <div class="img-ss rounded-circle bg-light border mr-3"></div>
                    Light
                </div>
                <div class="sidebar-bg-options selected" id="sidebar-dark-theme">
                    <div class="img-ss rounded-circle bg-dark border mr-3"></div>
                    Dark
                </div>
                <p class="settings-heading mt-2">HEADER SKINS</p>
                <div class="color-tiles mx-0 px-4">
                    <div class="tiles success"></div>
                    <div class="tiles warning"></div>
                    <div class="tiles danger"></div>
                    <div class="tiles primary"></div>
                    <div class="tiles info"></div>
                    <div class="tiles dark"></div>
                    <div class="tiles default border"></div>
                </div>
            </div>
       
  {% block bootstrap5_extra_script %}
    <script src="{% static 'js/js/off-canvas.js' %}"></script>
    <script src="{% static 'js/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'js/js/template.js' %}"></script>
    <script src="{% static 'js/js/settings.js' %}"></script>
  {% endblock %}
    

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1 {% if user.is_authenticated %}, shrink-to-fit=no {% endif %}">
        <link rel="shortcut icon" href="{% static 'favicon/favicon.ico' %}">

		<title>{% block title %}{% endblock %}</title>
		{% load bootstrap5 %}
        {% bootstrap_css %}
		<!-- Loading main css file -->
        {% bootstrap_javascript %}
        {% if not 'javascript_in_head'|bootstrap_setting %}
            {% bootstrap_javascript %}
        {% endif %}
		<script src="{% static '/js/jquery.min.js' %}"></script>
		{% comment %} <script src="{% static '/js/jquery.min.js' %}"></script> {% endcomment %}
		<!--[if lt IE 9]>
		<script src="js/ie-support/html5.js"></script>
		<script src="js/ie-support/respond.js"></script>
		<![endif]-->
			
		{% block extra_css %}
			
		{% endblock %}
				
	</head>


	<body data-media-url="{% get_media_prefix %}">
		{% if user.is_authenticated %}
		<div class="container-scroller">
			{% include 'admin_navbar.html' %}	
			<div class="row">
				<div class="col-9">
				</div>
				<div class="col-3">
					{% block add_content_link %}
					{% endblock %}	
				</div>
			</div>
		{% else %}
		{% include '_navbar.html' %}
		{% endif %}

		
		{% if user.is_authenticated %}
		{% else %}
        <div class="main-content">
			<main class="main-content">
				{% block bootstrap5_before_content %}{% endblock %}

                <br>
				<div class=" container">
		{% endif %}
					{% block bootstrap5_content %}
                	{% endblock %}
				</div>
                {% block bootstrap5_after_content %}{% endblock %}
        </div>
		<br><br>
		
		{% if user.is_authenticated %}
			{% include 'admin_footer_.html' %}
				</div>
			</div>
		</div>
	</div>
</div>
		{% else %}
			{% include '_footer.html' %}
		{% endif %}
			
	<!-- Bootstrap JavaScript if it is in body -->
	<script src="{% static 'js/dashboard.js' %}"></script>
	<script src="{% static 'js\vendor.bundle.base.js' %}"></script>
	{% block bootstrap5_extra_script %}{% endblock %}
    </body>
</html>

templates/sent.html
{% extends 'base.html' %}

<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="red" class="bi bi-check-circle" viewBox="0 0 16 16">
  <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
  <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
</svg>